@aiAgentsServiceHost = {{$dotenv AZURE_AI_AGENTS_SERVICE_HOSTNAME}}
@aiAgentsServiceAccessToken = {{$dotenv AZURE_AI_AGENTS_SERVICE_ACCESS_TOKEN}}
@apiVersion = 2024-12-01-preview

# output AZURE_AI_AGENTS_SERVICE_HOSTNAME string = concat(
#  substring(aiModelsDeploy.outputs.projectDiscoveryUrl, 0, lastIndexOf(aiModelsDeploy.outputs.projectDiscoveryUrl, '/')),
#  '/agents/v1.0',
#  aiModelsDeploy.outputs.projectId)


### PREP THE FILE AND VECTOR STORE

# @name uploadFile
curl {{aiAgentsServiceHost}}/files?api-version={{apiVersion}} -H "Authorization: Bearer {{aiAgentsServiceAccessToken}}" -F purpose="assistants" -F file="@examples/files/food-holidays.txt"

###

# @name createVectorStore
POST {{aiAgentsServiceHost}}/vector_stores?api-version={{apiVersion}}
Authorization: Bearer {{aiAgentsServiceAccessToken}}
Content-Type: application/json

{
    "name": "holidays-recipe-agent-vs"
}

###

@vectorStoreId = {{createVectorStore.response.body.$.id}}
@fileId = {{uploadFile.response.body.$.data[0].id}}

# @name attachFileToVectorStore
POST {{aiAgentsServiceHost}}/vector_stores/{{vectorStoreId}}/files?api-version={{apiVersion}}
Authorization: Bearer {{aiAgentsServiceAccessToken}}
Content-Type: application/json

{
    "file_id": "{{fileId}}"
}

### CREATE AN AGENT, THREAD, MESSAGES

# @name createAgent
POST {{aiAgentsServiceHost}}/assistants?api-version={{apiVersion}}
Authorization: Bearer {{aiAgentsServiceAccessToken}}
Content-Type: application/json

{
    "name": "holidays-recipe-agent",
    "instructions": "You are a helpful assistant. You answer questions about upcoming events based on your calendar data. The current date is {{$localDatetime 'MM-DD-YYYY'}}. Do not make up events.",
    "model": "gpt-4o-mini",
    "tools": [
        { "type": "file_search" }
    ],
    "tool_resources": { 
        "file_search": { 
            "vector_store_ids": [ "{{vectorStoreId}}" ] 
        } 
    }
}

###

# @name createThread
POST {{aiAgentsServiceHost}}/threads?api-version={{apiVersion}}
Authorization: Bearer {{aiAgentsServiceAccessToken}}
Content-Type: application/json

###

@threadId = {{createThread.response.body.$.id}}

# @name addUserMessageToThread
POST {{aiAgentsServiceHost}}/threads/{{threadId}}/messages?api-version={{apiVersion}}
Authorization: Bearer {{aiAgentsServiceAccessToken}}
Content-Type: application/json

{
    "role": "user",
    "content": "What food holidays are coming up over the next week?"
}

### RUN THE THREAD

@agentId = {{createAgent.response.body.$.id}}

# @name runThread
POST {{aiAgentsServiceHost}}/threads/{{threadId}}/runs?api-version={{apiVersion}}
Authorization: Bearer {{aiAgentsServiceAccessToken}}
Content-Type: application/json

{
    "assistant_id": "{{agentId}}"
}

###

@runId = {{runThread.response.body.$.id}}

# @name checkRunStatus
GET {{aiAgentsServiceHost}}/threads/{{threadId}}/runs/{{runId}}?api-version={{apiVersion}}
Authorization: Bearer {{aiAgentsServiceAccessToken}}

###

# @name getRunResults
GET {{aiAgentsServiceHost}}/threads/{{threadId}}/messages?api-version={{apiVersion}}
Authorization: Bearer {{aiAgentsServiceAccessToken}}

### TODO: TEST FROM HERE DOWN... ADD A FILE VIA MESSAGE ATTACHMENT

# @name uploadMessageAttachment
curl {{aiAgentsServiceHost}}/files?api-version={{apiVersion}} -H "Authorization: Bearer {{aiAgentsServiceAccessToken}}" -F purpose="assistants" -F file="@examples/files/birthdays.txt"

###

@messageAttachmentFileId = {{{uploadMessageAttachment.response.body.$.data[0].id}}}

# @name addMessageAndAttachment
POST {{aiAgentsServiceHost}}/threads/{{threadId}}/messages?api-version={{apiVersion}}
Authorization: Bearer {{aiAgentsServiceAccessToken}}
Content-Type: application/json

{
    "role": "user",
    "content": "What food holidays are on the next two birthdays?",
    "attachment": [
        {
            "file_id": "{{messageAttachmentFileId}}",
            "tools": [
                { "type": "file_search" }
            ]
        }
    ]
}

### RUN THE THREAD AGAIN

# @name runThreadAgain
POST {{aiAgentsServiceHost}}/threads/{{threadId}}/runs?api-version={{apiVersion}}
Authorization: Bearer {{aiAgentsServiceAccessToken}}
Content-Type: application/json

{
    "assistant_id": "{{agentId}}"
}

###

@runId = {{runThreadAgain.response.body.$.id}}

# @name checkRunStatus
GET {{aiAgentsServiceHost}}/threads/{{threadId}}/runs/{{runId}}?api-version={{apiVersion}}
Authorization: Bearer {{aiAgentsServiceAccessToken}}

###

# @name getRunResults
GET {{aiAgentsServiceHost}}/threads/{{threadId}}/messages?api-version={{apiVersion}}
Authorization: Bearer {{aiAgentsServiceAccessToken}}

### CLEANUP

# @name deleteVectorStore
DELETE {{aiAgentsServiceHost}}/vector_stores/{{vectorStoreId}}?api-version={{apiVersion}}
Authorization: Bearer {{aiAgentsServiceAccessToken}}

###

# @name deleteFile
DELETE {{aiAgentsServiceHost}}/files/{{fileId}}?api-version={{apiVersion}}
Authorization: Bearer {{aiAgentsServiceAccessToken}}

###

# @name deleteThread
DELETE {{aiAgentsServiceHost}}/threads/{{threadId}}?api-version={{apiVersion}}
Authorization: Bearer {{aiAgentsServiceAccessToken}}

###

# @name deleteAgent
DELETE {{aiAgentsServiceHost}}/assistants/{{agentId}}?api-version={{apiVersion}}
Authorization: Bearer {{aiAgentsServiceAccessToken}}